pipeline{
    agent any
    environment{
        SONAR_HOME= tool "Sonar"
    }
    stages{
      
        stage("Clean Workspace and Code Checkout"){
            steps{
                cleanWs()
                git url:"https://github.com/DevMadhup/wanderlust.git", branch:"main"
            }
        }
        
        stage("SonarQube Code Analysis"){
            steps{
                withSonarQubeEnv("Sonar"){
                    sh "$SONAR_HOME/bin/sonar-scanner -Dsonar.projectName=wanderlust -Dsonar.projectKey=wanderlust"
                }
            }
        }
        
        stage("SonarQube Code Quality Gates"){
                steps{
                    timeout(time: 2, unit: "MINUTES"){
                        waitForQualityGate abortPipeline: false
                    }
                }
        }
        
        stage("OWASP Dependency Check"){
            steps{
                dependencyCheck additionalArguments: '--scan frontend/ backend/', odcInstallation: 'DC'
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            }
        }
        
        stage("Trivy filesystem Scan"){
            steps{
                sh "trivy fs --format table -o trivy-fs-report.html ."
            }
        }
        
        stage("Code Deploy: Docker-compose"){
            steps{    
               
                sh "docker-compose down && docker-compose up -d"
            }
        }
    }
}
